#!/bin/bash

set -e

PLATFORM=$(node -e 'console.log(process.platform)')
ARCH=$(node -e 'console.log(process.arch)')
ROOT=$(cd $(dirname $0)/../; pwd)
OUT_DIR=${ROOT}/compiled/${PLATFORM}

archs=${ARCH}
[ "${PLATFORM}" = "darwin" ] || [ "$ARCH" = "ia32" ] || archs="x64 ia32"

for arch in ${archs}
do
    echo "Build for ${PLATFORM} ${arch}"

    BUILD_ARCH=${arch//[a-z]/} ${ROOT}/node_modules/.bin/node-gyp rebuild --arch=${arch}

    target=build/Release/png_img.node
    strip -Sx ${target}

    out_dir=${OUT_DIR}/${arch}
    mkdir -p ${out_dir}
    mv ${target} ${out_dir}/

    echo "Result saved as ${out_dir}/$(basename ${target})"
done

if [ "$ALL" = "1" ]
then
    echo "Compile on Ubuntu"
    vagrant ssh -c "cd /vagrant ; npm install && npm run build"
fi
