#!/bin/bash

ROOT=$(cd $(dirname $0)/../; pwd)

##
testOn() {
    local os=$1
    case $os in
        lin*)
            echo "Test on Ubuntu"
            vagrant ssh linux -c "\
                cd png-img && \
                rsync -av --delete-after /vagrant/test/* ./test/ && \
                npm test \
                "
            ;;
        win*)
            echo "Test on Windows"
            # in ssh session './dev/test' prints only part of output,
            # so we need a workaround to print the whole output
            vagrant ssh win -c "\
                cd png-img && \
                rsync -av --delete-after /cygdrive/c/vagrant/test/* ./test/ && \
                ./dev/test 2>&1 | cat \
                "
            ;;
        all)
            testOn current
            testOn linux
            testOn windows
            ;;
        *)
            ${ROOT}/node_modules/.bin/mocha
            ;;
    esac

    echo
}

testOn ${OS}
